# Generated by Django 5.1.7 on 2025-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_todoitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.ManyToManyField(blank=True, to='myapp.pet'),
        ),
    ]
