# Generated by Django 5.1.7 on 2025-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_current_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
