# Generated by Django 5.1.7 on 2025-04-06 16:47

from django.db import migrations

def create_default_pets(apps, schema_editor):
    Pet = apps.get_model('myapp', 'Pet')
    default_pets = [
        {'name': 'Monkey', 'price': 20, 'image': 'images/monkey-pet.png'},
        {'name': 'Porcupine', 'price': 30, 'image': 'images/porcupine-pet.png'},
        {'name': 'Owl', 'price': 50, 'image': 'images/owl-pet.png'},
    ]
    for pet_data in default_pets:
        pet, created = Pet.objects.get_or_create(name=pet_data['name'])
        if created:
            pet.price = pet_data['price']
            pet.image = pet_data['image']
            pet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250406_1132'),
    ]

    operations = [
        migrations.RunPython(create_default_pets),
    ]
