# Generated by Django 5.1.7 on 2025-04-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_seed_default_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_pet', to='myapp.pet'),
        ),
    ]
