# Generated by Django 5.1.7 on 2025-04-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pet_remove_profile_points_profile_coins_profile_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coins',
            new_name='points',
        ),
    ]
