# Generated by Django 5.1.7 on 2025-04-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_coins_profile_points'),
    ]

    operations = [
    ]
