# Generated by Django 5.1.7 on 2025-04-06 16:47

from django.db import migrations

def create_default_pets(apps, schema_editor):
    Pet = apps.get_model('myapp', 'Pet')
    default_pets = [
        {'name': 'Monkey', 'price': 20, 'image': 'images/monkey-pet.png'},
        {'name': 'Porcupine', 'price': 30, 'image': 'images/porcupine-pet.png'},
        {'name': 'Owl', 'price': 50, 'image': 'images/owl-pet.png'},
    ]
    for pet in default_pets:
        Pet.objects.get_or_create(name=pet['name'], defaults=pet)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250406_1132'),
    ]

    operations = [
        migrations.RunPython(create_default_pets),
    ]
